// ngx-fudis/.storybook/addons/version-selector/VersionSelector.tsx
import React, { useEffect, useState } from "react";
import { Button, WithTooltip, TooltipLinkList } from "storybook/internal/components";

interface VersionsResponse {
  versions: string[];
  latest: string;
}

export default function VersionSelector() {
  const [versions, setVersions] = useState<string[]>([]);
  const [currentVersion, setCurrentVersion] = useState<string>("next");
  const [hasError, setHasError] = useState<boolean>(false);

  useEffect(() => {
    const isProd = window.location.hostname === "fudis.funidata.fi";
    const versionsUrl = isProd
      ? "https://fudis.funidata.fi/ngx/v/versions.json"
      : "ngx/v/versions.json";

    fetch(versionsUrl)
      .then((response) => {
        if (!response.ok) {
          throw new Error(`Failed to load versions: ${response.status}`);
        }
        return response.json() as Promise<VersionsResponse>;
      })
      .then((res) => {
        let loadedVersions = res?.versions ?? [];
        loadedVersions = [...loadedVersions].reverse();

        const majorVersions: string[] = [];
        loadedVersions = loadedVersions.filter((version) => {
          const major = version.split(".")[0];
          if (majorVersions.includes(major)) {
            return true;
          }

          if (majorVersions.length < 3) {
            majorVersions.push(major);
            return true;
          }

          return false;
        });

        loadedVersions = loadedVersions.filter(
          (version) =>
            !["8.0.0", "8.3.0", "8.3.1", "8.3.2", "10.1.0"].includes(version) &&
            !version.includes("rc"),
        );

        setVersions(loadedVersions);

        let selectedVersion = res.latest;
        const pathParts = window.location.href.split("/");
        const vIndex = pathParts.indexOf("v");
        if (vIndex !== -1 && vIndex + 1 < pathParts.length) {
          const possibleVersion = decodeURIComponent(pathParts[vIndex + 1]);
          if (loadedVersions.includes(possibleVersion)) {
            selectedVersion = possibleVersion;
          }
        }

        setCurrentVersion(selectedVersion ?? loadedVersions[0] ?? "next");
      })
      .catch(() => {
        setHasError(true);
      });
  }, []);

  const navigateToVersion = (version: string) => {
    const currentUrl = new URL(window.location.href);
    currentUrl.protocol = "https:";
    currentUrl.hostname = "fudis.funidata.fi";

    if (currentUrl.pathname.startsWith("/ngx/v/")) {
      currentUrl.pathname = currentUrl.pathname.replace(
        /(^\/ngx\/v\/)[^/]+/,
        `$1${encodeURIComponent(version)}`,
      );
      window.location.href = currentUrl.toString();
      return;
    }

    window.location.href = `https://fudis.funidata.fi/ngx/v/${encodeURIComponent(version)}/index.html${currentUrl.search}${currentUrl.hash || ""}`;
  };

  const links = versions.map((version) => ({
    id: version,
    title: "v" + version,
    onClick: () => navigateToVersion(version),
    active: currentVersion === version,
  }));

  if (hasError || versions.length === 0) return null;

  return (
    <WithTooltip
      placement="bottom"
      trigger="click"
      closeOnOutsideClick
      tooltip={<TooltipLinkList links={links} />}
    >
      <Button ariaLabel={"Fudis version " + currentVersion}>
        {currentVersion === "next" ? "next" : "v" + currentVersion}
      </Button>
    </WithTooltip>
  );
}

// ngx-fudis/projects/ngx-fudis/src/storybook-docs/version-selector/version-selector.component.ts
import { Component, OnInit } from '@angular/core';
import { FormControl } from '@angular/forms';
import { HttpClient } from '@angular/common/http';

import { FudisSelectOption } from '../../lib/types/forms';
import { NgxFudisModule } from '../../lib/ngx-fudis.module';

interface VersionsResponse {
  versions: string[];
  latest: string;
}

@Component({
  selector: 'fudis-version-selector',
  templateUrl: './version-selector.component.html',
  styleUrls: ['./version-selector.component.scss'],
  standalone: true,
  imports: [NgxFudisModule],
})
export class VersionSelectorComponent implements OnInit {
  private _versions: string[] = [];
  private _control = new FormControl<FudisSelectOption<string> | null>(null);
  private _error = false;

  get versions(): string[] {
    return this._versions;
  }

  get control() {
    return this._control;
  }

  get error(): boolean {
    return this._error;
  }

  constructor(private http: HttpClient) {}

  ngOnInit(): void {
    const isProd = window.location.hostname === 'fudis.funidata.fi';

    const versionsUrl = isProd
      ? 'https://fudis.funidata.fi/ngx/v/versions.json'
      : 'ngx/v/versions.json';

    this.http.get<VersionsResponse>(versionsUrl).subscribe({
      next: (res) => {
        this._versions = res?.versions ?? [];

        // reverse so that latest versions are first
        this._versions = this._versions.reverse();

        // filter the version list so that only the latest three major versions are shown
        const majorVersions = new Array<string>();
        this._versions = this._versions.filter((v) => {
          const major = v.split('.')[0];
          if (majorVersions.includes(major)) {
            return true;
          } else if (majorVersions.length < 3) {
            majorVersions.push(major);
            return true;
          }
          return false;
        });

        // filter to exclude rc versions and remove problematic versions, currently:
        //  8.0.0, 8.3.0, 8.3.1 and 8.3.2

        this._versions = this._versions.filter(
          (v) => !['8.0.0', '8.3.0', '8.3.1', '8.3.2'].includes(v) && !v.includes('rc'),
        );

        // after redirection, if the current selected version can be found in the url, set it as the selected value, else select latest
        const pathParts = window.top!.location.href.split('/');
        let currentVersion: string = res.latest;
        const vIndex = pathParts.indexOf('v');
        if (vIndex !== -1 && vIndex + 1 < pathParts.length) {
          const possibleVersion = decodeURIComponent(pathParts[vIndex + 1]);
          if (this._versions.includes(possibleVersion)) {
            currentVersion = possibleVersion;
          }
        }
        this._control.setValue(
          {
            label: currentVersion,
            value: currentVersion,
          },
          { emitEvent: false },
        );
      },
      error: () => {
        this._error = true;
      },
    });

    this._control.valueChanges.subscribe((v) => {
      if (!v) return;
      const selected = v as FudisSelectOption<string> | null;
      const val = selected?.value ?? null;
      if (!val) return;
      const cur = new URL(window.top!.location.href);
      cur.protocol = 'https:';
      cur.hostname = 'fudis.funidata.fi';

      let target: string;

      // If the current pathname already contains /ngx/v/<version>, replace only the version part
      if (cur.pathname.startsWith('/ngx/v/')) {
        cur.pathname = cur.pathname.replace(
          /(^\/ngx\/v\/)[^/]+/,
          `$1${encodeURIComponent(String(val))}`,
        );
        target = cur.toString();
        window.top!.location.href = target;
      } else {
        // Otherwise, build production URL that points to the selected version (this happens in the developement environment)
        target = `https://fudis.funidata.fi/ngx/v/${encodeURIComponent(String(val))}/index.html${cur.search}${cur.hash || ''}`;
        window.top!.location.href = target;
      }
    });
  }
}

<div class="fudis-version-selector">
  <ng-container *ngIf="error">
    <fudis-body-text class="fudis-version-selector--unavailable fudis-text-emptystate">
      Version selector unavailable
    </fudis-body-text>
  </ng-container>
  <ng-container *ngIf="!error">
    <fudis-select
      [size]="'xs'"
      [control]="control"
      [label]="'Version'"
      [selectionClearButton]="false"
    >
      <ng-template fudisSelectOptions>
        <fudis-select-option
          *ngFor="let v of versions"
          [data]="{ value: v, label: v }"
        ></fudis-select-option>
      </ng-template>
    </fudis-select>
  </ng-container>
</div>
